manifest.xml: drop settings for android.hardware.broadcastradio
as it seems not fully configured, and cause build errors like
the following now:

    [ 85% 46356/54295] Install out/host/linux-x86/bin/checkvintf
    [ 85% 46357/54295] build out/target/product/hikey960/obj/PACKAGING/check_vintf_all_intermediates/check_vintf_vendor.log
    FAILED: out/target/product/hikey960/obj/PACKAGING/check_vintf_all_intermediates/check_vintf_vendor.log
    /bin/bash -c "( out/host/linux-x86/bin/checkvintf --check-one --dirmap /vendor:out/target/product/hikey960/vendor --property ro.boot.product.vendor.sku= > out/target/product/hikey960/obj/PACKAGING/check_vintf_all_intermediates/check_vintf_vendor.log 2>&1 ) || ( cat out/target/product/hikey960/obj/PACKAGING/check_vintf_all_intermediates/check_vintf_vendor.log && exit 1 )"
    Checking vendor manifest.
    getDeviceHalManifest: Reading VINTF information.
    Sysprop ro.boot.product.vendor.sku=
    Fetch 'out/target/product/hikey960/vendor/etc/vintf/manifest.xml': OK
    getDeviceHalManifest: status from fetching VINTF information: -22
    getDeviceHalManifest: -22 VINTF parse error: Illformed file: /vendor/etc/vintf/manifest.xml: Could not parse element with name <hal> in element <manifest>: <hal> android.hardware.broadcastradio has no instance. Fix by adding <fqname>.
    ERROR: Cannot fetch vendor manifest.
    Checking vendor matrix.
    getDeviceCompatibilityMatrix: Reading VINTF information.
    Fetch 'out/target/product/hikey960/vendor/etc/vintf/compatibility_matrix.xml': OK
    getDeviceCompatibilityMatrix: Successfully processed VINTF information

Test: build & boot test with hikey/hikey960 droid builds

Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>
Change-Id: Iea64d64b848371b59b10f5da03aee71567d7901e